#%% [markdown]
# # Combine and Clean Data
# This is just a notebook file I can use to merge data generated by seperate
# scripts into fewer data files. I have to do this fairly often so it makes
# sense to keep the code somewhere I think
#
# ## $I_{\pm}$ for $k=5$ one dimensional CAs
# each row is outputed in parallel so they have to be combined to be useful
# %%
import pandas as pd
from glob import glob

dfs = []
for file in glob('../data/k5/pid/*_ipm.csv'):
    rule = int(file.split('/')[-1].split('_')[0])
    print('Adding rule ', rule)
    df_row = pd.read_csv(file, index_col = 0)
    df_row['rule'] = rule
    dfs.append(df_row)

print('Merging dfs')
big_ipm_df = pd.concat(dfs)
big_ipm_df.to_csv('../data/k5/pid/ipm_ugly.csv', index=None)
# %% [markdown]
# ### change column names
# the atom names that come out of `dit` are very ugly. lets change them with
# this function I wrote.
# %%
import re

def pretty_labels_map(atom_labels):
    """
    transforms all of these crazy tuples into the notation used in williams and
    beer I_min PID
    """
    rename_map = {}
    for label in atom_labels:
        new_label = str(label)

        # eliminate commas and spaces
        new_label = new_label.replace(',', '')
        new_label = new_label.replace(' ', '')

        # replace braces
        new_label = new_label.replace('(', '{')
        new_label = new_label.replace(')', '}')

        # separate digits with colons
        while re.search(r'\d\d', new_label):
            new_label = re.sub(r'(\d)(\d)', r'\1:\2', new_label)

        # put them in a map
        rename_map[label] = new_label[1:-1]
    
    return rename_map

ipm_df = pd.read_csv('../data/k5/pid/ipm_ugly.csv')

lab_map = pretty_labels_map(ipm_df.columns)
lab_map['rule'] = 'rule'

ipm_df = ipm_df.rename(columns = lab_map)
ipm_df.to_csv('../data/k5/pid/ipm.csv')
# %%
